[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "james"
version = "0.2.0"
description = "pygame ui library"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Louis Masarei-Boulton" }]
dependencies = [
    "pygame-ce>=2.5.8"
]

[tool.setuptools]
package-dir = {"" = "src"}
